name: Build for Mac

on: 
  # A release, pre-release, or draft of a release is published
  release:
    types: published
  # Manual
  workflow_dispatch: {}

jobs:
  buildForMac:
      name: Build for Mac
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          targetPlatform:
            - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            #- StandaloneWindows # Build a Windows 32-bit standalone.
            #- StandaloneWindows64 # Build a Windows 64-bit standalone.
            #- StandaloneLinux64 # Build a Linux 64-bit standalone.
            #- iOS # Build an iOS player.
            #- Android # Build an Android .apk standalone app.
            #- WebGL # WebGL.
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            lfs: true

        # Cache
        - name: Cache libraries
          uses: actions/cache@v2
          with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: |
              Library-

        # Build
        - name: Build project
          uses: game-ci/unity-builder@v2
          id: buildStep
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: ${{ matrix.targetPlatform }}
            versioning: Semantic
            buildName: Fridaythe13th-${{ matrix.targetPlatform }}
            
        # Grant executable permissions
        - name: Grant executable permissions
          run: |
            sudo chmod -R 777 /build/Fridaythe13th-${{ matrix.targetPlatform }}/Fridaythe13th-${{ matrix.targetPlatform }}.app/Contents/MacOS/Friday\ the\ 13th\ Game
        
        # Tar Mac build files to maintain file permissions
        - name: Tar Mac build files
          run: |
            sudo tar -cvf Fridaythe13th.tar /build/Fridaythe13th-${{ matrix.targetPlatform }}
            
        - name: Test non-mac build step for a mac build
          if: ${{ matrix.targetPlatform }} != "StandaloneOSX"
          run: |
            echo "Non mac build step run on mac build!"

        # Output build
        - name: Output build as artifact
          uses: actions/upload-artifact@v3
          with:
            name: Build-${{ matrix.targetPlatform }}
            path: build/Fridaythe13th.tar
